[tool.poetry]
name = "port"
version = "0.0.0"
description = "Port package with Data DataSubmission"
authors = ["Emiel van der Veen <e.vanderveen@eyra.co>"]
include = [{ path = "port/assets", format = ["sdist", "wheel"] }]

[tool.poetry.dependencies]
python = ">=3.11"
pandas = "^3.0.0"

[tool.poetry.group.test.dependencies]
pytest = "^9.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
